name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Fix npm version
        run: npm install -g npm@10.8.2

      - name: Install Dependencies
        env:
         NODE_ENV: development
        run: |
          npm install --include=dev 
            env: 
          NPM_CONFIG_FETCH_RETRIES: 5
          NPM_CONFIG_FETCH_RETRY_MINTIMEOUT: 20000
          NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT: 120000

      - name: Build Web
        run: |
          ls -la
          ls node_modules/.bin
          npx react-scripts build

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Promptora-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
